In [6]:
import plotly.express as px
import pandas as pd

In [10]:
df = pd.read_csv("/placement_data.csv")
print(df)

    cgpa      iq  placement
0   3.53  137.02          1
1   2.38  110.99          0
2   2.99  137.71          0
3   2.61  135.73          0
4   3.69   98.67          0
..   ...     ...        ...
95  2.47  148.26          0
96  3.49  133.30          1
97  3.86  147.46          1
98  2.39  106.72          0
99  3.06  146.98          1

[100 rows x 3 columns]

In [11]:
df.head()

   cgpa      iq  placement
0  3.53  137.02          1
1  2.38  110.99          0
2  2.99  137.71          0
3  2.61  135.73          0
4  3.69   98.67          0

In [13]:
df['cgpa'].value_counts()

cgpa
3.06    3
2.47    3
3.99    2
2.45    2
3.43    2
       ..
3.77    1
2.92    1
2.75    1
3.86    1
2.39    1
Name: count, Length: 77, dtype: int64

In [14]:
px.bar(df, x="cgpa",color = 'cgpa')

In [18]:
px.bar(df,x='cgpa',color='cgpa',color_discrete_sequence = ['red','green','brown','purple'])

In [24]:
data = df.groupby(['cgpa']).size().rename('count').reset_index()

In [25]:
data.head()

   cgpa  count
0  2.04      1
1  2.10      2
2  2.14      1
3  2.15      1
4  2.19      2

In [26]:
px.bar(data,x='cgpa',y='count',color='cgpa',text='count')

In [27]:
px.data.gapminder()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4
...,...,...,...,...,...,...,...,...
1699,Zimbabwe,Africa,1987,62.351,9216418,706.157306,ZWE,716
1700,Zimbabwe,Africa,1992,60.377,10704340,693.420786,ZWE,716
1701,Zimbabwe,Africa,1997,46.809,11404948,792.449960,ZWE,716
1702,Zimbabwe,Africa,2002,39.989,11926563,672.038623,ZWE,716
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

In [32]:
data_canada = px.data.gapminder().query("country == 'Canada'")

In [33]:
data_canada.head()

    country continent  year  lifeExp       pop    gdpPercap iso_alpha  iso_num
240  Canada  Americas  1952    68.75  14785584  11367.16112       CAN      124
241  Canada  Americas  1957    69.96  17010154  12489.95006       CAN      124
242  Canada  Americas  1962    71.30  18985849  13462.48555       CAN      124
243  Canada  Americas  1967    72.13  20819767  16076.58803       CAN      124
244  Canada  Americas  1972    72.88  22284500  18970.57086       CAN      124

In [34]:
px.bar(data_canada,x='country',y='year',color='country',text='year')

In [36]:
data_canada.head(2)

    country continent  year  lifeExp       pop    gdpPercap iso_alpha  iso_num
240  Canada  Americas  1952    68.75  14785584  11367.16112       CAN      124
241  Canada  Americas  1957    69.96  17010154  12489.95006       CAN      124

In [41]:
px.bar(data_canada, x="country", y="year",
       hover_data=["lifeExp", "gdpPercap"],color='lifeExp',
       labels={"year": "year of country"}, height=400)

In [43]:
px.data.medals_long()

        nation   medal  count
0  South Korea    gold     24
1        China    gold     10
2       Canada    gold      9
3  South Korea  silver     13
4        China  silver     15
5       Canada  silver     12
6  South Korea  bronze     11
7        China  bronze      8
8       Canada  bronze     12

In [48]:
long_data = px.data.medals_long()

In [49]:
long_data.head()

        nation   medal  count
0  South Korea    gold     24
1        China    gold     10
2       Canada    gold      9
3  South Korea  silver     13
4        China  silver     15

In [50]:
px.bar(long_data,x='medal',y='count',color='medal',
       title="long formatted data")

In [51]:
px.data.medals_wide()

        nation  gold  silver  bronze
0  South Korea    24      13      11
1        China    10      15       8
2       Canada     9      12      12

In [54]:
wide_data = px.data.medals_wide()

In [55]:
wide_data.head()

        nation  gold  silver  bronze
0  South Korea    24      13      11
1        China    10      15       8
2       Canada     9      12      12

In [58]:
px.bar(wide_data,x='nation',y=['gold','silver','bronze'],
       title="wide formatted data")

In [59]:
long_data

        nation   medal  count
0  South Korea    gold     24
1        China    gold     10
2       Canada    gold      9
3  South Korea  silver     13
4        China  silver     15
5       Canada  silver     12
6  South Korea  bronze     11
7        China  bronze      8
8       Canada  bronze     12

In [60]:
px.bar(long_data,x='medal',y='count',color='nation',
       pattern_shape_sequence=['.','x','+'])