In [1]:
import plotly.express as px

In [2]:
df =px.data.tips()

In [3]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
fig = px.box(df,y="total_bill")
fig.show()

In [5]:
fig = px.box(df,x="time",y="total_bill")
fig.show()

In [7]:
fig = px.box(df,x="time",y="total_bill",points="all")
fig.show()

In [8]:
fig = px.box(df,x="time",y="total_bill",color="smoker")
fig.show()

In [11]:
df = px.data.tips()
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [12]:
fig = px.box(df,x="time",y="total_bill",color="smoker",notched=True,hover_data="day")
fig.show()